# layout/shell.py

from functools import lru_cache

import dash
import dash_mantine_components as dmc
from dash import ALL, Input, Output, State, callback, dcc, html
from dash_iconify import DashIconify

from layout.footer import shell_footer
from layout.header import shell_header
from layout.input import legend_toggle, scenario_legend_accordion, unit_toggle
from src import paths
from src.config import DEFAULT_SELECTIONS, LINKS
from src.equipment import load_library  # adjust if path differs
from utils.display_registry import format_emission_scenario_id_short


@lru_cache(maxsize=1)
def _get_equipment_library():
    """Lazy-load and cache the equipment library as a dict."""
    return load_library(paths.EQUIPMENT_JSON).model_dump()


def build_shell(page_content):
    """
    Build a Dash Mantine AppShell-based layout around the current page content.
    `page_content` will be dash.page_container from app.py.
    """

    # ---- global stores ----
    equipment_library = _get_equipment_library()
    global_state = [
        dcc.Store(id="metadata-store", storage_type="session"),
        dcc.Store(
            id="load-data-path-store",
            storage_type="session",
            data=None,
        ),
        dcc.Store(id="equipment-initial-store", storage_type="session", data=equipment_library),
        dcc.Store(id="equipment-store", storage_type="session", data=equipment_library),
        dcc.Store(
            id="selected-equipment-store",
            storage_type="session",
            data=DEFAULT_SELECTIONS.EQUIPMENT_SCENARIO.value,
        ),
        dcc.Store(
            id="equipment-scenario-number-map",
            storage_type="session",
            data={},
        ),
        dcc.Store(
            id="displayed-equipment-store",
            storage_type="session",
            data=DEFAULT_SELECTIONS.EQUIPMENT_SCENARIO.value,
        ),
        dcc.Store(
            id="selected-emissions-store",
            storage_type="session",
            data=DEFAULT_SELECTIONS.EMISSIONS_SCENARIO.value,
        ),
        dcc.Store(
            id="session-store", storage_type="session", data={}
        ),  # session_id generated by clientside callback in app.py
        dcc.Store(id="selected-building-store", storage_type="session"),
        dcc.Store(id="load-summary-store", storage_type="session", data=None),
        dcc.Store(id="pending-load-data-store", storage_type="session", data=None),
        dcc.Store(id="scale-info-store", storage_type="session", data=None),
        # Scenario group selections (persisted across page navigation)
        dcc.Store(id="equipment-scenario-group-store", storage_type="session", data="default"),
        dcc.Store(id="emission-scenario-group-store", storage_type="session", data="year"),
    ]

    header = dmc.AppShellHeader(
        dmc.Group(
            [
                shell_header(),
            ],
            h="100%",
            px="md",
            justify="space-between",
            align="center",
        )
    )

    navbar = dmc.AppShellNavbar(
        id="navbar",
        children=dmc.ScrollArea(
            build_navbar_content(),
            type="hover",
            offsetScrollbars=True,
            scrollbarSize=10,
            scrollHideDelay=1000,
            styles={
                "thumb": {
                    "backgroundColor": "var(--mantine-color-gray-2)",
                },
            },
            p="0px 10px 0px 0px",
        ),
        p="md",
    )

    main = dmc.AppShellMain(
        dmc.Stack(
            [
                dcc.Location(id="url", refresh=False),
                dmc.NotificationContainer(id="notification-container", position="top-right"),
                *global_state,
                html.Div(page_content),
            ],
            gap="md",
        )
    )

    # ---- FOOTER: wrap your existing footer ----
    footer = dmc.Paper(
        shell_footer(),
        p=0,
    )

    appshell = dmc.AppShell(
        [
            header,
            navbar,
            main,
            footer,
        ],
        header={"height": 120},
        # footer={"height": 120},
        navbar={
            "width": 350,
            "breakpoint": "sm",
            "collapsed": {"mobile": True, "desktop": False},
        },
        padding="md",
        id="appshell",
    )

    return dmc.MantineProvider(appshell)


def build_navbar_content():
    pages = sorted(
        dash.page_registry.values(),
        key=lambda p: p.get("order", 0),
    )

    page_links = [
        dmc.NavLink(
            label=page["name"],
            href=page["path"],
            id={"type": "navbar-link", "path": page["path"]},
            active=False,  # will be controlled by callback
        )
        for page in pages
    ]

    docs_link = dmc.Anchor(
        dmc.Group(
            [
                DashIconify(icon="material-symbols-light:menu-book-outline", width=25),
                "Documentation",
            ],
            gap="xs",  # Gap between icon and text
            align="center",
        ),
        href=LINKS.DOCS_URL.value,
        target="_blank",
        underline=False,
        fz="sm",
    )

    return dmc.Stack(
        children=[
            dmc.Stack(page_links, gap="sm"),
            dmc.Divider(),
            unit_toggle(),
            dmc.Divider(),
            legend_toggle(),
            html.Div(
                id="legend-container",
                children=scenario_legend_accordion(),
                style={"display": "none"},  # Hidden by default
            ),
            dmc.Divider(),
            dmc.Stack(  # external resources section
                [docs_link],
                gap="xs",
            ),
        ],
        gap="md",
    )


@callback(
    Output({"type": "navbar-link", "path": ALL}, "active"),
    Input("url", "pathname"),
    State({"type": "navbar-link", "path": ALL}, "id"),
)
def set_active_navlinks(pathname, link_ids):
    # pathname: current path, e.g. "/emissions"
    # link_ids: list of {"type": "navbar-link", "path": "..."} dicts

    if pathname is None:
        return [False] * len(link_ids)

    return [(link_id["path"] == pathname) for link_id in link_ids]


@callback(
    Output("appshell", "navbar"),
    Input("burger", "opened"),
    State("appshell", "navbar"),
    prevent_initial_call=False,
)
def toggle_navbar(opened, navbar):
    # Defensive copy
    navbar = dict(navbar or {})
    collapsed = dict(navbar.get("collapsed", {}))

    collapsed["mobile"] = not opened
    collapsed["desktop"] = not opened

    navbar["collapsed"] = collapsed
    return navbar


@callback(
    Output("legend-container", "style"),
    Input("legend-toggle", "checked"),
)
def toggle_legend_visibility(checked):
    """Show/hide the legend accordion based on toggle state."""
    if checked:
        return {"display": "block"}
    return {"display": "none"}


@callback(
    Output("equipment-legend-content", "children"),
    Input("equipment-store", "data"),
    Input("selected-equipment-store", "data"),
)
def update_equipment_legend(equipment_data, selected_ids):
    """Populate the equipment legend with ID to name mappings."""
    if not equipment_data or not selected_ids:
        return dmc.Text("No scenarios selected", c="dimmed", size="sm")

    scenarios = equipment_data.get("equipment_scenarios", [])
    selected_scenarios = [s for s in scenarios if s.get("eq_scen_id") in selected_ids]

    if not selected_scenarios:
        return dmc.Text("No scenarios selected", c="dimmed", size="sm")

    rows = []
    for i, scen in enumerate(selected_scenarios):
        scen_id = scen.get("eq_scen_id", "")
        scen_name = scen.get("eq_scen_name", scen_id)
        short_id = str(i + 1)  # Display position (1-5) instead of scenario ID suffix

        rows.append(
            dmc.Group(
                [
                    dmc.Tooltip(
                        dmc.Badge(short_id, size="sm", variant="light", color="blue", w=40),
                        label=scen_name,
                        position="right",
                        withArrow=True,
                    ),
                    dmc.Text(scen_name, size="sm", truncate=True),
                ],
                gap="xs",
                wrap="nowrap",
            )
        )

    return dmc.Stack(rows, gap="xs")


@callback(
    Output("emission-legend-content", "children"),
    Input("metadata-store", "data"),
    Input("selected-emissions-store", "data"),
)
def update_emission_legend(metadata_data, selected_ids):
    """Populate the emission legend with ID to name mappings."""
    if not metadata_data or not selected_ids:
        return dmc.Text("No scenarios selected", c="dimmed", size="sm")

    scenarios = metadata_data.get("emission_settings", [])
    selected_scenarios = [s for s in scenarios if s.get("em_scen_id") in selected_ids]

    if not selected_scenarios:
        return dmc.Text("No scenarios selected", c="dimmed", size="sm")

    rows = []
    for scen in selected_scenarios:
        scen_id = scen.get("em_scen_id", "")
        scen_name = scen.get("em_scen_name", scen_id)
        short_id = format_emission_scenario_id_short(scen_id)

        rows.append(
            dmc.Group(
                [
                    dmc.Tooltip(
                        dmc.Badge(short_id, size="sm", variant="light", color="green", w=40),
                        label=scen_name,
                        position="right",
                        withArrow=True,
                    ),
                    dmc.Text(scen_name, size="sm", truncate=True),
                ],
                gap="xs",
                wrap="nowrap",
            )
        )

    return dmc.Stack(rows, gap="xs")


@callback(
    Output("equipment-scenario-number-map", "data"),
    Input("selected-equipment-store", "data"),
)
def update_equipment_number_map(selected_ids):
    """Create mapping of scenario_id -> display_number (1-5)."""
    if not selected_ids:
        return {}
    return {scen_id: i + 1 for i, scen_id in enumerate(selected_ids)}
