"""Print a verification report: tool vs independent reference, and spreadsheet agreement.

    python -m tests.verification.report            # Markdown to stdout
    python -m tests.verification.report --csv out.csv

Numbers are generated by the same code the verification tests run, so the
report always reflects what the test suite checks.
"""

import argparse
import logging

import pandas as pd

from tests.verification.cases import comparison_table

LABELS = {
    "elec_kWh": "Electricity [MWh]",
    "gas_kWh": "Gas [MWh]",
    "total_kgCO2e": "Total emissions [t CO2e]",
}
SCENARIO_NAMES = {
    "eq_scenario_1": "Gas boiler + chiller",
    "eq_scenario_3": "20% AWHP + gas backup",
    "eq_scenario_4": "100% AWHP + electric backup",
}


def summary_table(full: pd.DataFrame) -> pd.DataFrame:
    """Compact table: Cambium long-run grid, key metrics, MWh / t, tool vs reference."""
    t = full[(full["grid"] == "cambium_lrmer_2025") & full["metric"].isin(LABELS)].copy()
    t[["tool", "reference"]] = t[["tool", "reference"]] / 1000  # kWh->MWh, kg->t
    t["metric"] = t["metric"].map(LABELS)
    t["scenario"] = t["scenario"].map(SCENARIO_NAMES)
    t["Δ [%]"] = t["rel_diff"] * 100
    return t.rename(
        columns={
            "building": "Building",
            "scenario": "Scenario",
            "metric": "Quantity",
            "tool": "Tool",
            "reference": "Independent",
        }
    )[["Building", "Scenario", "Quantity", "Tool", "Independent", "Δ [%]"]]


def to_markdown(df: pd.DataFrame) -> str:
    """Minimal Markdown table (avoids a tabulate dependency)."""

    def fmt(v):
        return f"{v:,.1f}" if isinstance(v, float) else str(v)

    t = df.copy()
    t["Δ [%]"] = t["Δ [%]"].map(lambda v: f"{v:+.4f}")
    lines = ["| " + " | ".join(t.columns) + " |", "|" + "---|" * len(t.columns)]
    lines += ["| " + " | ".join(fmt(v) for v in row) + " |" for row in t.itertuples(index=False)]
    return "\n".join(lines)


def spreadsheet_summary() -> str:
    """Agreement with the legacy hand calculations in tests/testing_cases.xlsx."""
    from tests import test_verification_spreadsheet as sheet

    diffs, superseded, known = [], 0, 0
    for case in sheet.FIXTURE["cases"]:
        site = sheet._site(case["id"])
        for hour in case["hours"]:
            row = site.loc[pd.Timestamp(hour["timestamp"])]
            superseded += len(hour["superseded"])
            known += len(hour["known_differences"])
            for check in hour["checks"]:
                tool = row[check["column"]]
                tool = 0.0 if pd.isna(tool) else tool / check["divisor"]
                if abs(check["value"]) > 1e-9:
                    diffs.append(abs(tool - check["value"]) / abs(check["value"]))
    n_cases = len(sheet.FIXTURE["cases"])
    return (
        f"Spreadsheet hand calculations: {len(diffs)} non-zero hourly values across {n_cases} scenarios "
        f"agree within {max(diffs) * 100:.2f} % (median {pd.Series(diffs).median() * 100:.4f} %); "
        f"{superseded} values superseded by a later method change; "
        f"{known} open method difference(s)."
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--csv", help="also write the full comparison (all metrics/grids) to CSV")
    args = parser.parse_args()

    logging.disable(logging.WARNING)
    full = comparison_table()

    print(to_markdown(summary_table(full)))
    worst = full.loc[full["rel_diff"].abs().idxmax()]
    print(
        f"\n{len(full)} comparisons; largest |Δ| = {abs(worst['rel_diff']) * 100:.2e} % "
        f"({worst['building']}/{worst['scenario']}/{worst['grid']}/{worst['metric']})"
    )
    print(spreadsheet_summary())
    if args.csv:
        full.to_csv(args.csv, index=False)
        print(f"Full comparison written to {args.csv}")


if __name__ == "__main__":
    main()
